package com.example.project3;

/**
 * Represents a person in the clinic management system.
 * This class serves as superclass for Patient and Provider classes
 *
 * @author Vy Nguyen, Shahnaz Khan
 */
public class Person implements Comparable<Person>{

    // Instance variables
    protected Profile profile;

    /**
     * Default constructor that initializes the profile instance to null
     */
    public Person() {
        this.profile = null;
    }

    /**
     * Constructs a new Person object with the given profile.
     *
     * @param profile the profile of the person
     */
    public Person(Profile profile) {
        this.profile = profile;
    }

    /**
     * Retrieves the profile of the person.
     *
     * @return the profile of the person
     */
    public Profile getProfile() {
        return profile;
    }

    /**
     * Compares this person with another person based on their profiles
     *
     * @param other the other person to compare with
     * @return a negative integer, zero, or positive as this person is
     * less than, equal to, or greater than the other person.
     */
    @Override
    public int compareTo(Person other) {
        return this.profile.compareTo(other.profile);
    }

    /**
     * Determines whether the specified object is equal to the current Person instance.
     *
     * @param obj the object to compare to this Person instance
     * @return true if the specified object is equal to the current Person instance based on their profiles, false otherwise
     */
    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Person) {
            Person other = (Person) obj;
            return this.profile.equals(other.profile);
        }
        return false;
    }

    /**
     * Returns a string representation of the Person object.
     * The string is generated by calling the toString method of the profile instance variable.
     *
     * @return a string representation of the Person object based on the profile information
     */
    @Override
    public String toString() {
        return profile.toString();
    }
}